# Importing Pandas

In [1]:
import pandas as pd #pandas ko short main pd se change kia 
import numpy as np

## Creating a pandas series

In [2]:
numbers = [10, 20, 30, 40] #list of numbers 
series = pd.Series(numbers) # creating a series 
print(series) #Yaha per hum ne print kia hay series ko

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
numbers=np.array([1,2,3,4,5,6,7]) #Numpy array ka use krr k series kese banayee let see
series=pd.Series(numbers) #creating series for numpy array
print(series) #Yaha per hum ne print kia hay series ko

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

## Creating a pandas dataframe

In [4]:
data={
    "Name":["Ishfaq khan","Kashif wazir","Majid wazir","Afaq khan","Wasif wazir","Hassan wazir"],
    "Age":[20,22,28,25,20,29],
    "Marks":[792,845,840,826,675,899]
    }
df=pd.DataFrame(data)
df.reset_index()

   index          Name  Age  Marks
0      0   Ishfaq khan   20    792
1      1  Kashif wazir   22    845
2      2   Majid wazir   28    840
3      3     Afaq khan   25    826
4      4   Wasif wazir   20    675
5      5  Hassan wazir   29    899

### Head Function
This shows the first 5 rows of the dataset or DataFrame

In [5]:
df.head().reset_index()

   index          Name  Age  Marks
0      0   Ishfaq khan   20    792
1      1  Kashif wazir   22    845
2      2   Majid wazir   28    840
3      3     Afaq khan   25    826
4      4   Wasif wazir   20    675

### Tail Function
This shows the last 5 rows of the ataset or DataFrame

In [6]:
df.tail().reset_index()

   index          Name  Age  Marks
0      1  Kashif wazir   22    845
1      2   Majid wazir   28    840
2      3     Afaq khan   25    826
3      4   Wasif wazir   20    675
4      5  Hassan wazir   29    899

### Shape Attribute

In [ ]:
print(df) #To Print the dataframe
print("Shape=",df.shape) # To Print the shape of dataframe

           Name  Age  Marks
0   Ishfaq khan   20    792
1  Kashif wazir   22    845
2   Majid wazir   28    840
3     Afaq khan   25    826
4   Wasif wazir   20    675
5  Hassan wazir   29    899
Shape= (6, 3)

### Columns Attribute

In [ ]:
df.columns #To check the columns

Index(['Name', 'Age', 'Marks'], dtype='str')

## Selecting Columns from DataFrame

In [26]:
print("\n Age Column is =\n",df["Age"]) #Select a single column
print("\n Name and Marks columns is =\n",df[["Name","Marks"]]) #select a multiple columns
print("\n Age,Marks,Name columns is =\n",df[["Age","Marks","Name"]])#select a multiple columns

 Age Column is =
 0    20
1    22
2    28
3    25
4    20
5    29
Name: Age, dtype: int64

 Name and Marks columns is =
            Name  Marks
0   Ishfaq khan    792
1  Kashif wazir    845
2   Majid wazir    840
3     Afaq khan    826
4   Wasif wazir    675
5  Hassan wazir    899

 Age,Marks,Name columns is =
    Age  Marks          Name
0   20    792   Ishfaq khan
1   22    845  Kashif wazir
2   28    840   Majid wazir
3   25    826     Afaq khan
4   20    675   Wasif wazir
5   29    899  Hassan wazir

### Basic Summary of Data

In [27]:
df.describe()

             Age       Marks
count   6.000000    6.000000
mean   24.000000  812.833333
std     3.949684   75.898397
min    20.000000  675.000000
25%    20.500000  800.500000
50%    23.500000  833.000000
75%    27.250000  843.750000
max    29.000000  899.000000