# Importing library

In [1]:
import pandas as pd

### Read csv file

In [2]:
df=pd.read_csv("sales_data.csv")
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

### GroupBy
Common aggregation functions sum(),mean(),count(),min(),max(),median()

In [3]:
#Groupby with single column
sales_region=df.groupby("Region")["Sales_Amount"].sum()
sales_min=df.groupby("Region")["Sales_Amount"].min()
sales_max=df.groupby("Region")["Sales_Amount"].max()
sales_count=df.groupby("Region")["Sales_Amount"].count()

print("\n Region Sales:\n",sales_region)
print("\n Region Minimam Sales:\n",sales_min)
print("\n Region Maximam Sales:\n",sales_max)
print("\n Region Sales Count:\n",sales_count)

 Region Sales:
 Region
East     1259792.93
North    1369612.51
South    1154250.86
West     1235608.93
Name: Sales_Amount, dtype: float64

 Region Minimam Sales:
 Region
East     113.40
North    119.72
South    114.59
West     100.12
Name: Sales_Amount, dtype: float64

 Region Maximam Sales:
 Region
East     9948.71
North    9989.04
South    9961.96
West     9933.22
Name: Sales_Amount, dtype: float64

 Region Sales Count:
 Region
East     263
North    267
South    226
West     244
Name: Sales_Amount, dtype: int64

### Groupby with multiple columns

In [4]:
sales_region=df.groupby(["Region","Product_Category"])["Sales_Amount"].sum()
sales_min=df.groupby(["Region","Product_Category"])["Sales_Amount"].min()
sales_max=df.groupby(["Region","Product_Category"])["Sales_Amount"].max()
sales_count=df.groupby(["Region","Product_Category"])["Sales_Amount"].count()

print("\n Region Sales:\n",sales_region)
print("\n Region Minimam Sales:\n",sales_min)
print("\n Region Maximam Sales:\n",sales_max)
print("\n Region Sales Count:\n",sales_count)

 Region Sales:
 Region  Product_Category
East    Clothing            356670.40
        Electronics         303101.42
        Food                325864.87
        Furniture           274156.24
North   Clothing            372977.22
        Electronics         342666.29
        Food                258985.65
        Furniture           394983.35
South   Clothing            269517.74
        Electronics         293663.96
        Food                301187.51
        Furniture           289881.65
West    Clothing            314309.00
        Electronics         304067.97
        Food                315735.51
        Furniture           301496.45
Name: Sales_Amount, dtype: float64

 Region Minimam Sales:
 Region  Product_Category
East    Clothing            182.37
        Electronics         198.25
        Food                242.38
        Furniture           113.40
North   Clothing            119.72
        Electronics         349.41
        Food                213.04
        Furniture           252.41
South   Clothing            594.79
        Electronics         245.46
        Food                114.59
        Furniture           783.18
West    Clothing            100.12
        Electronics         189.48
        Food                777.74
        Furniture           152.60
Name: Sales_Amount, dtype: float64

 Region Maximam Sales:
 Region  Product_Category
East    Clothing            9744.52
        Electronics         9683.85
        Food                9948.71
        Furniture           9709.70
North   Clothing            9972.66
        Electronics         9850.10
        Food                9989.04
        Furniture           9976.52
South   Clothing            9519.30
        Electronics         9914.15
        Food                9895.57
        Furniture           9961.96
West    Clothing            9605.34
        Electronics         9733.46
        Food                9933.22
        Furniture           9638.64
Name: Sales_Amount, dtype: float64

 Region Sales Count:
 Region  Product_Category
East    Clothing            76
        Electronics         65
        Food                63
        Furniture           59
North   Clothing            76
        Electronics         65
        Food                48
        Furniture           78
South   Clothing            55
        Electronics         57
        Food                58
        Furniture           56
West    Clothing            61
        Electronics         59
        Food                57
        Furniture           67
Name: Sales_Amount, dtype: int64

### Using Multiple Aggregation Functions

In [6]:
df1=df.groupby("Region")["Sales_Amount"].agg(["max","min","sum"]) #multiple aggregation with single column
df1.reset_index()

  Region      max     min         sum
0   East  9948.71  113.40  1259792.93
1  North  9989.04  119.72  1369612.51
2  South  9961.96  114.59  1154250.86
3   West  9933.22  100.12  1235608.93

In [9]:
df2=df.groupby(["Region","Product_Category"])["Sales_Amount"].agg(["mean","max","min","sum"])#multiple aggregation with 2 columns
df2

                                mean      max     min        sum
Region Product_Category
East   Clothing          4693.031579  9744.52  182.37  356670.40
       Electronics       4663.098769  9683.85  198.25  303101.42
       Food              5172.458254  9948.71  242.38  325864.87
       Furniture         4646.715932  9709.70  113.40  274156.24
North  Clothing          4907.595000  9972.66  119.72  372977.22
       Electronics       5271.789077  9850.10  349.41  342666.29
       Food              5395.534375  9989.04  213.04  258985.65
       Furniture         5063.889103  9976.52  252.41  394983.35
South  Clothing          4900.322545  9519.30  594.79  269517.74
       Electronics       5151.999298  9914.15  245.46  293663.96
       Food              5192.888103  9895.57  114.59  301187.51
       Furniture         5176.458036  9961.96  783.18  289881.65
West   Clothing          5152.606557  9605.34  100.12  314309.00
       Electronics       5153.694407  9733.46  189.48  304067.97
       Food              5539.219474  9933.22  777.74  315735.51
       Furniture         4499.947015  9638.64  152.60  301496.45

### Using agg with Dictionary

In [10]:
df1=df.groupby("Region").agg({
    "Sales_Amount":["sum","mean","min","max"]
})
df1

       Sales_Amount
                sum         mean     min      max
Region
East     1259792.93  4790.087186  113.40  9948.71
North    1369612.51  5129.634869  119.72  9989.04
South    1154250.86  5107.304690  114.59  9961.96
West     1235608.93  5063.971025  100.12  9933.22

###  Resetting Index After GroupBy
This makes the output cleaner and easier to use

In [15]:
df1=df.groupby("Region").agg({
    "Sales_Amount":["sum","mean","min","max"],
    "Quantity_Sold":["sum","mean","min","max"],
    "Unit_Cost":["sum","mean","min","max"],
    "Unit_Price":["sum","mean","min","max"]
}).reset_index()
df1

  Region Sales_Amount                               Quantity_Sold             \
                  sum         mean     min      max           sum       mean
0   East   1259792.93  4790.087186  113.40  9948.71          6356  24.167300
1  North   1369612.51  5129.634869  119.72  9989.04          6705  25.112360
2  South   1154250.86  5107.304690  114.59  9961.96          5808  25.699115
3   West   1235608.93  5063.971025  100.12  9933.22          6486  26.581967

           Unit_Cost                              Unit_Price               \
  min max        sum         mean    min      max        sum         mean
0   1  49  653216.09  2483.711369  60.28  4991.68  719682.00  2736.433460
1   1  49  657678.56  2463.215581  83.64  4995.30  723408.06  2709.393483
2   1  49  552507.95  2444.725442  84.86  4920.46  611016.22  2703.611593
3   1  49  611901.95  2507.794877  61.50  4984.21  674333.84  2763.663279


      min      max
0  211.18  5402.28
1  167.12  5442.15
2  181.62  5253.07
3  175.29  5309.32

### Counting Values Using GroupBy

In [18]:
df4=df.groupby("Region")["Sales_Amount"].count().reset_index()
df4

  Region  Sales_Amount
0   East           263
1  North           267
2  South           226
3   West           244